#! /bin/sh

#### AUTOSTART ####

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
$HOME/.config/polybar/launch.sh &
feh --bg-fill ~/Wallpapers/wallhaven-y8yvxk.jpg &
greenclip daemon &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         4
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color       "#3c3836"
bspc config focused_border_color      "#cc241d"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
